// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RasdAI.DAL;

#nullable disable

namespace RasdAI.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260618145754_AddCreatedAt")]
    partial class AddCreatedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RasdAI.DAL.Entities.AIConversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MessagesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("AIConversations");
                });

            modelBuilder.Entity("RasdAI.DAL.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("TenantId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 18, 14, 57, 50, 359, DateTimeKind.Utc).AddTicks(7911),
                            CreatedByUserId = 3,
                            Email = "contact@arabian.com",
                            Name = "شركة المقاولات العربية",
                            Phone = "01099998888",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 18, 14, 57, 50, 360, DateTimeKind.Utc).AddTicks(762),
                            CreatedByUserId = 3,
                            Email = "info@alfath.com",
                            Name = "مجموعة الفتح التجارية",
                            Phone = "01288887777",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("RasdAI.DAL.Entities.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AIAnalysisResult")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("TenantId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("RasdAI.DAL.Entities.Deal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("AssignedUserId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("ClientId");

                    b.HasIndex("TenantId");

                    b.ToTable("Deals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 150000m,
                            AssignedUserId = 3,
                            ClientId = 1,
                            CreatedAt = new DateTime(2026, 6, 18, 14, 57, 50, 360, DateTimeKind.Utc).AddTicks(3508),
                            Status = "Won",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 2,
                            Amount = 75000m,
                            AssignedUserId = 3,
                            ClientId = 2,
                            CreatedAt = new DateTime(2026, 6, 18, 14, 57, 50, 360, DateTimeKind.Utc).AddTicks(5472),
                            Status = "Proposal",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("RasdAI.DAL.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DealId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DealId");

                    b.HasIndex("TenantId");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 18, 14, 57, 50, 360, DateTimeKind.Utc).AddTicks(6326),
                            DealId = 1,
                            DueDate = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Unpaid",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TotalAmount = 150000m
                        });
                });

            modelBuilder.Entity("RasdAI.DAL.Entities.Meeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AISummary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Transcript")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoFilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("RasdAI.DAL.Entities.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("TenantId");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            Content = "العميل مهتم جداً بعروض الأسعار البرمجية ويفضل الدفع الآجل.",
                            CreatedAt = new DateTime(2026, 6, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 3,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("RasdAI.DAL.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "SystemAdmin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Owner"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Accountant"
                        },
                        new
                        {
                            Id = 4,
                            Name = "SalesManager"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 6,
                            Name = "EmployeeManager"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Employee"
                        });
                });

            modelBuilder.Entity("RasdAI.DAL.Entities.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MeetingId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("MeetingId");

                    b.HasIndex("TenantId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedUserId = 3,
                            CreatedAt = new DateTime(2026, 6, 18, 14, 57, 50, 360, DateTimeKind.Utc).AddTicks(9425),
                            DueDate = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Todo",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Title = "متابعة عرض السعر مع مجموعة الفتح"
                        },
                        new
                        {
                            Id = 2,
                            AssignedUserId = 6,
                            CreatedAt = new DateTime(2026, 6, 18, 14, 57, 50, 361, DateTimeKind.Utc).AddTicks(1365),
                            DueDate = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "InProgress",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Title = "إعداد تقرير المبيعات الشهري"
                        });
                });

            modelBuilder.Entity("RasdAI.DAL.Entities.Tenant", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TenantId");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "شركة رصد للتطوير والاستشارات"
                        });
                });

            modelBuilder.Entity("RasdAI.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("RoleId");

                    b.HasIndex("TenantId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "owner@rasd.com",
                            FullName = "أحمد فهيم (المالك)",
                            PasswordHash = "AQAAAAIAAYagAAAAEJw...",
                            RoleId = 2,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 2,
                            Email = "salesmanager@rasd.com",
                            FullName = "محمد المبيعات (مدير المبيعات)",
                            ManagerId = 1,
                            PasswordHash = "AQAAAAIAAYagAAAAEJw...",
                            RoleId = 4,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 3,
                            Email = "sales@rasd.com",
                            FullName = "عمر البائع (مندوب مبيعات)",
                            ManagerId = 2,
                            PasswordHash = "AQAAAAIAAYagAAAAEJw...",
                            RoleId = 5,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 4,
                            Email = "accountant@rasd.com",
                            FullName = "منى الحسابات (المحاسب)",
                            ManagerId = 1,
                            PasswordHash = "AQAAAAIAAYagAAAAEJw...",
                            RoleId = 3,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 5,
                            Email = "empmanager@rasd.com",
                            FullName = "خالد المدير (مدير الموظفين)",
                            ManagerId = 1,
                            PasswordHash = "AQAAAAIAAYagAAAAEJw...",
                            RoleId = 6,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 6,
                            Email = "employee@rasd.com",
                            FullName = "زياد الموظف (موظف)",
                            ManagerId = 5,
                            PasswordHash = "AQAAAAIAAYagAAAAEJw...",
                            RoleId = 7,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("RasdAI.DAL.Entities.AIConversation", b =>
                {
                    b.HasOne("RasdAI.DAL.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RasdAI.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RasdAI.DAL.Entities.Client", b =>
                {
                    b.HasOne("RasdAI.DAL.Entities.User", "CreatedByUser")
                        .WithMany("ClientsCreated")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RasdAI.DAL.Entities.Tenant", "Tenant")
                        .WithMany("Clients")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RasdAI.DAL.Entities.Contract", b =>
                {
                    b.HasOne("RasdAI.DAL.Entities.Client", "Client")
                        .WithMany("Contracts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RasdAI.DAL.Entities.Tenant", "Tenant")
                        .WithMany("Contracts")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RasdAI.DAL.Entities.Deal", b =>
                {
                    b.HasOne("RasdAI.DAL.Entities.User", "AssignedUser")
                        .WithMany("AssignedDeals")
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RasdAI.DAL.Entities.Client", "Client")
                        .WithMany("Deals")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RasdAI.DAL.Entities.Tenant", "Tenant")
                        .WithMany("Deals")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedUser");

                    b.Navigation("Client");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RasdAI.DAL.Entities.Invoice", b =>
                {
                    b.HasOne("RasdAI.DAL.Entities.Deal", "Deal")
                        .WithMany("Invoices")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RasdAI.DAL.Entities.Tenant", "Tenant")
                        .WithMany("Invoices")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Deal");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RasdAI.DAL.Entities.Meeting", b =>
                {
                    b.HasOne("RasdAI.DAL.Entities.Tenant", "Tenant")
                        .WithMany("Meetings")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RasdAI.DAL.Entities.Note", b =>
                {
                    b.HasOne("RasdAI.DAL.Entities.Client", "Client")
                        .WithMany("Notes")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RasdAI.DAL.Entities.User", "CreatedByUser")
                        .WithMany("NotesCreated")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RasdAI.DAL.Entities.Tenant", "Tenant")
                        .WithMany("Notes")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RasdAI.DAL.Entities.TaskItem", b =>
                {
                    b.HasOne("RasdAI.DAL.Entities.User", "AssignedUser")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RasdAI.DAL.Entities.Meeting", "Meeting")
                        .WithMany("Tasks")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RasdAI.DAL.Entities.Tenant", "Tenant")
                        .WithMany("Tasks")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedUser");

                    b.Navigation("Meeting");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RasdAI.DAL.Entities.User", b =>
                {
                    b.HasOne("RasdAI.DAL.Entities.User", "Manager")
                        .WithMany("Reportees")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RasdAI.DAL.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RasdAI.DAL.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");

                    b.Navigation("Role");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RasdAI.DAL.Entities.Client", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Deals");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("RasdAI.DAL.Entities.Deal", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("RasdAI.DAL.Entities.Meeting", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("RasdAI.DAL.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("RasdAI.DAL.Entities.Tenant", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Contracts");

                    b.Navigation("Deals");

                    b.Navigation("Invoices");

                    b.Navigation("Meetings");

                    b.Navigation("Notes");

                    b.Navigation("Tasks");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("RasdAI.DAL.Entities.User", b =>
                {
                    b.Navigation("AssignedDeals");

                    b.Navigation("AssignedTasks");

                    b.Navigation("ClientsCreated");

                    b.Navigation("NotesCreated");

                    b.Navigation("Reportees");
                });
#pragma warning restore 612, 618
        }
    }
}
